(function () {
  'use strict';

  function prefixDepth(path, depth) {
    if (!depth || path.indexOf('http') === 0 || path.indexOf('mailto:') === 0) return path;
    return (depth > 0 ? '../'.repeat(depth) : '') + path;
  }

  function href(path, depth, isHome) {
    if (path.charAt(0) === '#') {
      if (isHome) return path;
      return prefixDepth('index.html', depth) + path;
    }
    return prefixDepth(path, depth);
  }

  function buildNavbarHTML(depth, isHome) {
    var h = href;
    var p = function (path) { return prefixDepth(path, depth); };

    return ''
      + '<div class="container navbar__inner">'
      + '<a href="' + h('#inicio', depth, isHome) + '" class="navbar__logo" aria-label="VOROX Academia — Inicio">'
      + '<img src="' + p('assets/logo-vorox-footer.png?v=white') + '" alt="VOROX Academia" class="logo logo--nav" width="171" height="48" />'
      + '</a>'
      + '<nav class="navbar__audience" aria-label="Audiencias">'
      + '<div class="nav-dropdown" data-dropdown="estudiantes" data-dropdown-hover>'
      + '<button class="nav-dropdown__trigger" type="button" aria-expanded="false" aria-haspopup="true">'
      + 'Estudiantes'
      + '<svg class="nav-dropdown__chevron" viewBox="0 0 12 12" width="12" height="12" aria-hidden="true"><path d="M2 4l4 4 4-4" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>'
      + '</button>'
      + '<div class="nav-dropdown__panel nav-dropdown__panel--stack" hidden>'
      + '<div class="nav-mega nav-mega--stack">'
      + '<div class="nav-mega__col"><p class="nav-mega__title">Carreras</p><div class="nav-mega__body">'
      + '<a href="' + h('ai-engineering.html', depth, isHome) + '" class="nav-mega__link">AI Engineering</a>'
      + '<a href="' + h('full-stack-development.html', depth, isHome) + '" class="nav-mega__link">Full Stack Development</a>'
      + '<a href="' + h('data-science.html', depth, isHome) + '" class="nav-mega__link">Data Science</a>'
      + '<a href="' + h('#prog-de', depth, isHome) + '" class="nav-mega__link">Data Engineering</a>'
      + '<a href="' + h('#prog-aa', depth, isHome) + '" class="nav-mega__link">AI Automation</a>'
      + '<a href="' + h('#prog-md', depth, isHome) + '" class="nav-mega__link">Marketing Digital</a>'
      + '<a href="' + h('#prog-da', depth, isHome) + '" class="nav-mega__link">Data Analyst</a>'
      + '<a href="' + h('#prog-ux', depth, isHome) + '" class="nav-mega__link">Diseño UX/UI</a>'
      + '<a href="' + h('#prog-cyber', depth, isHome) + '" class="nav-mega__link">Ciberseguridad</a>'
      + '<a href="' + h('#prog-robo', depth, isHome) + '" class="nav-mega__link">Robótica</a>'
      + '</div></div>'
      + '<div class="nav-mega__col"><p class="nav-mega__title">Cursos</p><div class="nav-mega__body">'
      + '<a href="' + h('data-science.html', depth, isHome) + '" class="nav-mega__link">Programa Data Science</a>'
      + '<a href="' + h('data-science/clases.html#modulo-01', depth, isHome) + '" class="nav-mega__link">Fundamentos de Data Science</a>'
      + '<a href="' + h('data-science/clases.html#modulo-02', depth, isHome) + '" class="nav-mega__link">Python para Ciencia de Datos</a>'
      + '<a href="' + h('data-science/clases.html#modulo-03', depth, isHome) + '" class="nav-mega__link">Estadística y Probabilidad</a>'
      + '<a href="' + h('data-science/clases.html#modulo-04', depth, isHome) + '" class="nav-mega__link">Exploración y Visualización (EDA)</a>'
      + '<a href="' + h('data-science/clases.html#modulo-05', depth, isHome) + '" class="nav-mega__link">Machine Learning Supervisado</a>'
      + '<a href="' + h('data-science/clases.html#modulo-06', depth, isHome) + '" class="nav-mega__link">Machine Learning No Supervisado</a>'
      + '<a href="' + h('data-science/clases.html#modulo-07', depth, isHome) + '" class="nav-mega__link">NLP, Series Temporales e IA</a>'
      + '<a href="' + h('data-science/clases.html#modulo-08', depth, isHome) + '" class="nav-mega__link">Proyecto Final y Empleabilidad</a>'
      + '<a href="' + h('ai-engineering.html', depth, isHome) + '" class="nav-mega__link">Programa AI Engineering</a>'
      + '<a href="' + h('full-stack-development.html', depth, isHome) + '" class="nav-mega__link">Programa Full Stack Development</a>'
      + '<a href="' + h('#prog-de', depth, isHome) + '" class="nav-mega__link">Programa Data Engineering</a>'
      + '<a href="' + h('#prog-aa', depth, isHome) + '" class="nav-mega__link">Programa AI Automation</a>'
      + '<a href="' + h('#prog-md', depth, isHome) + '" class="nav-mega__link">Programa Marketing Digital</a>'
      + '<a href="' + h('#prog-da', depth, isHome) + '" class="nav-mega__link">Programa Data Analyst</a>'
      + '<a href="' + h('#prog-ux', depth, isHome) + '" class="nav-mega__link">Programa Diseño UX/UI</a>'
      + '<a href="' + h('#prog-cyber', depth, isHome) + '" class="nav-mega__link">Programa Ciberseguridad</a>'
      + '<a href="' + h('#prog-robo', depth, isHome) + '" class="nav-mega__link">Programa Robótica</a>'
      + '</div></div>'
      + '<div class="nav-mega__col"><p class="nav-mega__title">Introductorios gratuitos</p><div class="nav-mega__body">'
      + '<a href="' + h('nivelacion/data-analyst.html', depth, isHome) + '" class="nav-mega__link">Nivelación Data Analyst</a>'
      + '<a href="' + h('nivelacion/data-science.html', depth, isHome) + '" class="nav-mega__link">Nivelación Data Science</a>'
      + '<a href="' + h('nivelacion/full-stack-development.html', depth, isHome) + '" class="nav-mega__link">Nivelación Full Stack Development</a>'
      + '<a href="' + h('nivelacion.html#nivelacion-data-engineering', depth, isHome) + '" class="nav-mega__link">Nivelación Data Engineering</a>'
      + '<a href="' + h('nivelacion/ai-engineering.html', depth, isHome) + '" class="nav-mega__link">Nivelación AI Engineering</a>'
      + '<a href="' + h('nivelacion.html#nivelacion-ai-automation', depth, isHome) + '" class="nav-mega__link">Nivelación AI Automation</a>'
      + '<a href="' + h('nivelacion.html#nivelacion-marketing', depth, isHome) + '" class="nav-mega__link">Nivelación Marketing Digital</a>'
      + '</div></div>'
      + '<div class="nav-mega__col"><p class="nav-mega__title">Workshops</p><div class="nav-mega__body">'
      + '<a href="' + h('#contacto', depth, isHome) + '" class="nav-mega__link">Prompt Engineering</a>'
      + '<a href="' + h('#contacto', depth, isHome) + '" class="nav-mega__link">Automatización con IA</a>'
      + '<a href="' + h('#contacto', depth, isHome) + '" class="nav-mega__link">Dashboards en Power BI</a>'
      + '<a href="' + h('#contacto', depth, isHome) + '" class="nav-mega__link">Prototipado UX en Figma</a>'
      + '<a href="' + h('#contacto', depth, isHome) + '" class="nav-mega__link">Git &amp; GitHub express</a>'
      + '</div></div>'
      + '</div></div></div>'
      + '<div class="nav-dropdown" data-dropdown="empresas" data-dropdown-hover>'
      + '<button class="nav-dropdown__trigger" type="button" aria-expanded="false" aria-haspopup="true">'
      + 'Empresas'
      + '<svg class="nav-dropdown__chevron" viewBox="0 0 12 12" width="12" height="12" aria-hidden="true"><path d="M2 4l4 4 4-4" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>'
      + '</button>'
      + '<div class="nav-dropdown__panel nav-dropdown__panel--stack" hidden>'
      + '<div class="nav-mega nav-mega--stack">'
      + '<div class="nav-mega__col"><p class="nav-mega__title">Campus empleo</p><div class="nav-mega__body">'
      + '<a href="' + h('plataforma/campus-empleo.html', depth, isHome) + '" class="nav-mega__link">Publicar vacantes y recibir candidatos</a>'
      + '</div></div>'
      + '<div class="nav-mega__col"><p class="nav-mega__title">Contratar talento</p><div class="nav-mega__body">'
      + '<a href="' + h('#contacto', depth, isHome) + '" class="nav-mega__link">Graduados VOROX listos para producir</a>'
      + '</div></div>'
      + '<div class="nav-mega__col"><p class="nav-mega__title">Capacitación</p><div class="nav-mega__body">'
      + '<a href="' + h('#contacto', depth, isHome) + '" class="nav-mega__link">Programas a medida para tu equipo</a>'
      + '</div></div>'
      + '<div class="nav-mega__col"><p class="nav-mega__title">Consultoría</p><div class="nav-mega__body">'
      + '<a href="' + h('#contacto', depth, isHome) + '" class="nav-mega__link">Asesoramiento en transformación digital e IA</a>'
      + '</div></div>'
      + '</div></div></div>'
      + '</nav>'
      + '<div class="navbar__actions">'
      + '<div class="navbar__buttons">'
      + '<a href="' + h('plataforma/aula-virtual.html', depth, isHome) + '" class="btn btn--cta btn--sm">Aula</a>'
      + '</div>'
      + '<div class="more-menu-wrap">'
      + '<button class="more-menu__btn" id="moreMenuBtn" type="button" aria-label="Menú" aria-expanded="false" aria-haspopup="true">'
      + '<svg viewBox="0 0 24 24" width="22" height="22" aria-hidden="true"><circle cx="5" cy="12" r="1.8" fill="currentColor"/><circle cx="12" cy="12" r="1.8" fill="currentColor"/><circle cx="19" cy="12" r="1.8" fill="currentColor"/></svg>'
      + '</button>'
      + '<div class="more-menu more-menu--full" id="moreMenu" hidden>'
      + '<p class="more-menu__label">Herramientas</p>'
      + '<a href="' + h('plataforma/editor-codigo.html', depth, isHome) + '">Editor de código</a>'
      + '<a href="' + h('plataforma/campus-empleo.html', depth, isHome) + '">Campus empleo</a>'
      + '<p class="more-menu__label">Sitio</p>'
      + '<a href="' + h('nosotros.html', depth, isHome) + '">Nosotros</a>'
      + '<a href="' + h('#carreras', depth, isHome) + '">Programas</a>'
      + '<a href="' + h('#comunidad', depth, isHome) + '">Comunidad</a>'
      + '<a href="' + h('#faq', depth, isHome) + '">Preguntas frecuentes</a>'
      + '<a href="' + h('#contacto', depth, isHome) + '">Contacto</a>'
      + '</div></div>'
      + '<button class="navbar__toggle" id="navToggle" aria-label="Menú móvil"><span></span><span></span><span></span></button>'
      + '</div></div>'
      + '<div class="mobile-nav" id="mobileNav" hidden>'
      + '<div class="mobile-nav__tabs">'
      + '<button class="mobile-nav__tab active" data-mobile-tab="estudiantes" type="button">Estudiantes</button>'
      + '<button class="mobile-nav__tab" data-mobile-tab="empresas" type="button">Empresas</button>'
      + '</div>'
      + '<div class="mobile-nav__panel" id="mobilePanelEstudiantes">'
      + '<details class="mobile-nav__group"><summary>Carreras</summary>'
      + '<a href="' + h('ai-engineering.html', depth, isHome) + '">AI Engineering</a>'
      + '<a href="' + h('full-stack-development.html', depth, isHome) + '">Full Stack Development</a>'
      + '<a href="' + h('data-science.html', depth, isHome) + '">Data Science</a>'
      + '<a href="' + h('#prog-de', depth, isHome) + '">Data Engineering</a>'
      + '<a href="' + h('#prog-aa', depth, isHome) + '">AI Automation</a>'
      + '<a href="' + h('#prog-md', depth, isHome) + '">Marketing Digital</a>'
      + '<a href="' + h('#prog-da', depth, isHome) + '">Data Analyst</a>'
      + '<a href="' + h('#prog-ux', depth, isHome) + '">Diseño UX/UI</a>'
      + '<a href="' + h('#prog-cyber', depth, isHome) + '">Ciberseguridad</a>'
      + '<a href="' + h('#prog-robo', depth, isHome) + '">Robótica</a>'
      + '</details>'
      + '<details class="mobile-nav__group"><summary>Cursos</summary>'
      + '<a href="' + h('data-science.html', depth, isHome) + '">Programa Data Science</a>'
      + '<a href="' + h('data-science/clases.html#modulo-01', depth, isHome) + '">Fundamentos de Data Science</a>'
      + '<a href="' + h('data-science/clases.html#modulo-02', depth, isHome) + '">Python para Ciencia de Datos</a>'
      + '<a href="' + h('data-science/clases.html#modulo-03', depth, isHome) + '">Estadística y Probabilidad</a>'
      + '<a href="' + h('data-science/clases.html#modulo-04', depth, isHome) + '">Exploración y Visualización (EDA)</a>'
      + '<a href="' + h('data-science/clases.html#modulo-05', depth, isHome) + '">Machine Learning Supervisado</a>'
      + '<a href="' + h('data-science/clases.html#modulo-06', depth, isHome) + '">Machine Learning No Supervisado</a>'
      + '<a href="' + h('data-science/clases.html#modulo-07', depth, isHome) + '">NLP, Series Temporales e IA</a>'
      + '<a href="' + h('data-science/clases.html#modulo-08', depth, isHome) + '">Proyecto Final y Empleabilidad</a>'
      + '<a href="' + h('ai-engineering.html', depth, isHome) + '">Programa AI Engineering</a>'
      + '<a href="' + h('full-stack-development.html', depth, isHome) + '">Programa Full Stack Development</a>'
      + '<a href="' + h('#prog-de', depth, isHome) + '">Programa Data Engineering</a>'
      + '<a href="' + h('#prog-aa', depth, isHome) + '">Programa AI Automation</a>'
      + '<a href="' + h('#prog-md', depth, isHome) + '">Programa Marketing Digital</a>'
      + '<a href="' + h('#prog-da', depth, isHome) + '">Programa Data Analyst</a>'
      + '<a href="' + h('#prog-ux', depth, isHome) + '">Programa Diseño UX/UI</a>'
      + '<a href="' + h('#prog-cyber', depth, isHome) + '">Programa Ciberseguridad</a>'
      + '<a href="' + h('#prog-robo', depth, isHome) + '">Programa Robótica</a>'
      + '</details>'
      + '<details class="mobile-nav__group"><summary>Introductorios gratuitos</summary>'
      + '<a href="' + h('nivelacion/data-analyst.html', depth, isHome) + '">Nivelación Data Analyst</a>'
      + '<a href="' + h('nivelacion/data-science.html', depth, isHome) + '">Nivelación Data Science</a>'
      + '<a href="' + h('nivelacion/full-stack-development.html', depth, isHome) + '">Nivelación Full Stack Development</a>'
      + '<a href="' + h('nivelacion.html#nivelacion-data-engineering', depth, isHome) + '">Nivelación Data Engineering</a>'
      + '<a href="' + h('nivelacion/ai-engineering.html', depth, isHome) + '">Nivelación AI Engineering</a>'
      + '<a href="' + h('nivelacion.html#nivelacion-ai-automation', depth, isHome) + '">Nivelación AI Automation</a>'
      + '<a href="' + h('nivelacion.html#nivelacion-marketing', depth, isHome) + '">Nivelación Marketing Digital</a>'
      + '</details>'
      + '<details class="mobile-nav__group"><summary>Workshops</summary>'
      + '<a href="' + h('#contacto', depth, isHome) + '">Prompt Engineering</a>'
      + '<a href="' + h('#contacto', depth, isHome) + '">Automatización con IA</a>'
      + '<a href="' + h('#contacto', depth, isHome) + '">Dashboards en Power BI</a>'
      + '<a href="' + h('#contacto', depth, isHome) + '">Prototipado UX en Figma</a>'
      + '<a href="' + h('#contacto', depth, isHome) + '">Git &amp; GitHub express</a>'
      + '</details></div>'
      + '<div class="mobile-nav__panel" id="mobilePanelEmpresas" hidden>'
      + '<details class="mobile-nav__group"><summary>Campus empleo</summary>'
      + '<a href="' + h('plataforma/campus-empleo.html', depth, isHome) + '">Publicar vacantes y recibir candidatos</a>'
      + '</details>'
      + '<details class="mobile-nav__group"><summary>Contratar talento</summary>'
      + '<a href="' + h('#contacto', depth, isHome) + '">Graduados VOROX listos para producir</a>'
      + '</details>'
      + '<details class="mobile-nav__group"><summary>Capacitación</summary>'
      + '<a href="' + h('#contacto', depth, isHome) + '">Programas a medida para tu equipo</a>'
      + '</details>'
      + '<details class="mobile-nav__group"><summary>Consultoría</summary>'
      + '<a href="' + h('#contacto', depth, isHome) + '">Asesoramiento en transformación digital e IA</a>'
      + '</details></div>'
      + '<div class="mobile-nav__extras">'
      + '<p class="mobile-nav__group-title">Herramientas</p>'
      + '<a href="' + h('plataforma/editor-codigo.html', depth, isHome) + '">Editor de código</a>'
      + '<a href="' + h('plataforma/campus-empleo.html', depth, isHome) + '">Campus empleo</a>'
      + '<p class="mobile-nav__group-title">Sitio</p>'
      + '<a href="' + h('nosotros.html', depth, isHome) + '">Nosotros</a>'
      + '<a href="' + h('#comunidad', depth, isHome) + '">Comunidad</a>'
      + '<a href="' + h('#faq', depth, isHome) + '">FAQ</a>'
      + '</div>'
      + '<div class="mobile-nav__actions">'
      + '<a href="' + h('plataforma/aula-virtual.html', depth, isHome) + '" class="btn btn--cta btn--sm btn--full">Aula</a>'
      + '</div></div>';
  }

  function render() {
    var mount = document.querySelector('[data-site-nav]');
    if (!mount) return;
    var depth = parseInt(mount.getAttribute('data-nav-depth') || '0', 10);
    var isHome = mount.hasAttribute('data-nav-home');
    mount.innerHTML = buildNavbarHTML(depth, isHome);
  }

  window.VoroxSiteNav = { render: render, buildNavbarHTML: buildNavbarHTML };
  render();
})();
